# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#target 'schemeTest' do
#  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  def shared_pod
    pod 'GoogleUtilities', :modular_headers => true
  end


  # Pods for schemeTest
  target 'schemeTestA' do
	 shared_pod
  end

  target 'schemeTestB' do
	 shared_pod
  end

#end
