# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExNaverMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExNaverMap
  pod 'NMapsMap'
  pod 'SnapKit', '~> 5.6.0'
  target 'ExNaverMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExNaverMapUITests' do
    # Pods for testing
  end

end
