# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExIntroBannerTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExIntroBannerTest
  pod 'SnapKit', '~> 4.0.0'
  target 'ExIntroBannerTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExIntroBannerTestUITests' do
    # Pods for testing
  end

end
