# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExAdmob' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExAdmob

  target 'ExAdmobTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Google-Mobile-Ads-SDK'
  end

  target 'ExAdmobUITests' do
    # Pods for testing
  end

end
