# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExWebpTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExWebpTest
  pod 'SDWebImageWebPCoder'
  pod 'Kingfisher'#, '~> 5.0'
  pod "KingfisherWebP"
  target 'ExWebpTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExWebpTestUITests' do
    # Pods for testing
  end

end
